[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
nft_marketplace = "FYMA8ipmYc41tXx7MmoCZtyPE2JxTrpp1vLFb4DDwad2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "solana-keypair.json"

[workspace]
members = ["contracts/nft_marketplace"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
