[package]
name = "contract-service"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.18"
solana-client = "1.18"
anchor-client = "0.30"
shared = { path = "../shared" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }